services:
  db:
    image: postgres:15
    container_name: timebank-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: timebank
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - timebank-network
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
networks:
  timebank-network: