name: Build and Deploy

on:
  push:
    branches: [main]

env:
  REGISTRY: docker.io

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ secrets.REGISTRY_USER }}/timebank:latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build JAR
        run: mvn -B -pl boot package
      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME .
      - name: Log in to registry
        run: echo "${{ secrets.REGISTRY_TOKEN }}" | docker login -u "${{ secrets.REGISTRY_USER }}" --password-stdin $REGISTRY
      - name: Push image
        run: docker push $IMAGE_NAME
